start: arithmetic | constraint
%import common.WS 
%import common.CNAME 
%import common.SIGNED_NUMBER 
%import common.INT 
%import common.FLOAT 
%import common.NUMBER 
%import common.CPP_COMMENT 
%import common.LCASE_LETTER 
%ignore WS 
%ignore CPP_COMMENT 
?string: CNAME
?l_case: LCASE_LETTER

//  ----- Defined grammar below
!arithmetic_operator: 
arithmetic: "the sum between 1 and 2" | "the difference between 1 and 2"
operation: arithmetic | boolean
negative_constraint: "It is prohibited that" operation
constraint: negative_constraint
!boolean_operator: 
boolean: "the or between a and b"
