start: arithmetic | constraint | TERMINAL | entity | operation | there_is_clause
%import common.WS 
%import common.CNAME 
%import common.SIGNED_NUMBER 
%import common.INT 
%import common.FLOAT 
%import common.NUMBER 
%import common.CPP_COMMENT 
%ignore WS 
%ignore CPP_COMMENT 
?string: CNAME

//  ----- Defined grammar below
there_is_clause: ("it is" | "There") "is" entity
!arithmetic: "the sum between 1 and 2"
constraint: "it is prohibited that" arithmetic
entity: ("a" | "an")? string attribute
TERMINAL: "TERMINAL"
