start: arithmetic | constraint | TERMINAL | entity | operation | there_is_clause | a_rule
%import common.WS 
%import common.CNAME 
%import common.SIGNED_NUMBER 
%import common.INT 
%import common.FLOAT 
%import common.NUMBER 
%import common.CPP_COMMENT 
%import common.LCASE_LETTER 
%ignore WS 
%ignore CPP_COMMENT 
?string: CNAME
?l_case: LCASE_LETTER

//  ----- Defined grammar below
!arithmetic: "the sum between 1 and 2"
constraint: "it is prohibited that" arithmetic
entity: ("A" | "An" | "a" | "an")? string attribute
TERMINAL: "TERMINAL"
there_is_clause: ("it is" | "There") "is" entity
!a_rule: "This is a rule to import"
